openapi: 3.0.3
info:
  title: MoviesApi
  description: omdbapi.com
  version: 1.0.0
servers:
  - url: http://www.omdbapi.com
tags:
  - name: movies
    description: Movies list
  - name: movieDetails
    description: Movie details
paths:
  /?s:
    get:
      tags:
        - movies
      operationId: getMovies
      summary: Movies list
        parameters:
        - name: s
          in: query
          description: "Title of movie or series",
          required: true
          type: string
        - name: key
          in: path
          description: "Authentication key"
          required: true
          type: string
        - name: type
          in: path
          description: "Return movie or series"
          required: false
          type: string
          enum: [movie, series, episode]
        - name: page
          in: path
          description: "Page number to return"
          required: true
          schema:
            type: integer
        responses:
          "200":
            description: success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MoviesResponse'
          default:
            description: enexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorModel'
  /?i:
    get:
      tags:
        - movieDetails
      operationId: getMovieDetails
      summary: Movies Detailed information
        parameters:
        - name: i
          in: query
          description:  "A valid IMDb ID (e.g. tt0000001)",
          required: true
          type: string
        - name: key
          in: path
          description: "Authentication key"
          required: true
          type: string
        - name: plot
          in: path
          description: "Return short or full plot"
          required: false
          type: string
          enum: [short, full]
        responses:
          "200":
            description: success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MovieFull'
          default:
            description: enexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    MoviesResponse:
      type: object
      required:
        - Response
      properties:
        totalResults: 
          type: integer
        Response: 
          type: boolean
        Search: 
          type: array
          items: 
            $ref: '#/components/schemas/MovieShort'
    MovieShort:
      type: object
      required:
        - imdbID
      properties:
        Title: 
          type: string
        Year: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        Poster: 
          type: string
    MovieFull:
      type: object
      required:
        - imdbID
        - Title
      properties:
        Title: 
          type: string
        Year: 
          type: string
        Rated: 
          type: string
        Released: 
          type: string
        Runtime: 
          type: string
        Genre: 
          type: string
        Director: 
          type: string
        Writer: 
          type: string
        Actors: 
          type: string
        Plot: 
          type: string
        Language: 
          type: string
        Country: 
          type: string
        Awards: 
          type: string
        Poster: 
          type: string
        Ratings: 
          type: array
          items: 
            type: object
            items: 
              $ref: '#/components/schemas/MovieRating'
        Metascore: 
          type: string
        imdbRating: 
          type: string
        imdbVotes: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        DVD: 
          type: string
        BoxOffice: 
          type: string
        Production: 
          type: string
        Website: 
          type: string
        Response: 
          type: string
    MovieRating:
      required:
      - Source
      - Value
      type: object
      properties:
        Source: 
          type: string
        Value: 
          type: string
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        Response:
          type: boolean
        Error:
          type: string
