openapi: 3.0.3
info:
  title: MoviesApi
  description: omdbapi.com
  version: 1.0.0
servers:
  - url: http://www.omdbapi.com
tags:
  - name: movies
    description: Movies list
  - name: movieDetails
    description: Movie details
paths:
  ./:
    get:
      tags:
      - movies
      summary: Movies list
      operationId: getMovies
      parameters:
      - name: s
        in: query
        description: search
        required: true
        schema:
          type: string
      - name: type
        in: query
        description: search
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key
        required: true
        schema:
          type: string
      - name: page
        in: query
        description: query
        required: true
        schema:
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BooksVolumes'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
  ./:
    get:
      tags:
      - movieDetails
      summary: Movie details
      operationId: getMovieDetails
      parameters:
      - name: i
        in: query
        description: search
        required: true
        schema:
          type: string
      - name: key
        in: query
        description: key
        required: true
        schema:
          type: string
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieFull'
        default:
          description: enexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorModel'
components:
  schemas:
    MoviesResponse:
      type: object
      required:
        - Response
      properties:
        totalResults: 
          type: integer
        Response: 
          type: boolean
        Search: 
          type: array
          items: 
            $ref: '#/components/schemas/MovieShort'
    MovieShort:
      type: object
      required:
        - imdbID
      properties:
        Title: 
          type: string
        Year: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        Poster: 
    MovieFull:
      type: object
      required:
        - imdbID
        - Title
      properties:
        Title: 
          type: string
        Year: 
          type: string
        Rated: 
          type: string
        Released: 
          type: string
        Runtime: 
          type: string
        Genre: 
          type: string
        Director: 
          type: string
        Writer: 
          type: string
        Actors: 
          type: string
        Plot: 
          type: string
        Language: 
          type: string
        Country: 
          type: string
        Awards: 
          type: string
        Poster: 
          type: string
        Ratings: 
          type: array
          items: 
            type: object
            items: 
              $ref: '#/components/schemas/MovieRating'
        Metascore: 
          type: string
        imdbRating: 
          type: string
        imdbVotes: 
          type: string
        imdbID: 
          type: string
        Type: 
          type: string
        DVD: 
          type: string
        BoxOffice: 
          type: string
        Production: 
          type: string
        Website: 
          type: string
        Response: 
          type: string
    MovieRating:
      required:
      - Source
      - Value
      type: object
      properties:
        Source: 
          type: string
        Value: 
          type: string
    ErrorModel:
      required:
      - code
      - message
      type: object
      properties:
        Response:
          type: boolean
        Error:
          type: string
